name: test package

on: [push]

jobs:
  test:
    name: test package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: install dependencies
        uses: steebchen/flutter@v1.0.0
        with:
          args: pub get

      - name: run tests
        uses: steebchen/flutter@v1.0.0
        with:
          args: test
        env:
          VRCUser: ${{ secrets.VRCUser }}
          VRCPwd: ${{ secrets.VRCPwd }}
